# Generated by Django 5.1.5 on 2025-03-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se activó la alarma')),
                ('active_boolean', models.BooleanField(default=True, help_text='Indica si la alarma está activa')),
            ],
        ),
    ]
