# Generated by Django 5.1.5 on 2025-04-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='active_boolean',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='triggered_at',
        ),
        migrations.AddField(
            model_name='alert',
            name='estado',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='fecha',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='mensaje',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
