# Generated by Django 5.1.5 on 2025-04-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_alert_active_boolean_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('previous_repairs', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
