# Generated by Django 5.1.5 on 2025-04-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_computer'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='serial',
            field=models.CharField(default='desconocido', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
