# Generated by Django 5.1.5 on 2025-02-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(help_text='ID del sensor que activó la alarma', max_length=100)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se activó la alarma')),
                ('location', models.CharField(help_text='Ubicación del sensor', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('RESOLVED', 'Resuelta')], default='ACTIVE', help_text='Estado de la alarma', max_length=10)),
                ('additional_info', models.TextField(blank=True, help_text='Información adicional del evento', null=True)),
            ],
        ),
    ]
