# Generated by Django 5.1.5 on 2025-02-18 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Alert',
        ),
    ]
