# Generated by Django 5.1.5 on 2025-03-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_rename_movie_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='location',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='status',
        ),
    ]
