# Generated by Django 5.1.5 on 2025-03-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_remove_alert_additional_info_remove_alert_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='triggered_at',
            field=models.DateTimeField(help_text='Fecha y hora en que se activó la alarma'),
        ),
    ]
