# Generated by Django 5.1.5 on 2025-03-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_alert_triggered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='alert',
            name='triggered_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se activó la alarma'),
        ),
    ]
