# Generated by Django 5.1.5 on 2025-03-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_personalautorizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='authorized_personnel/')),
            ],
        ),
        migrations.DeleteModel(
            name='PersonalAutorizado',
        ),
    ]
