# Generated by Django 5.1.5 on 2025-03-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_authorizedpersonnel_delete_personalautorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='active_boolean',
            field=models.BooleanField(default=True, help_text='Indica si la alarma está activa'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='triggered_at',
            field=models.DateTimeField(help_text='Fecha y hora en que se activó la alarma'),
        ),
    ]
