# Generated by Django 5.1.5 on 2025-03-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_alert_active_boolean_alter_alert_triggered_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='AuthorizedPersonnel',
        ),
    ]
