# Generated by Django 5.1.5 on 2025-04-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_delete_alert_delete_authorizedpersonnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('previous_repairs', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
