# Generated by Django 5.1.5 on 2025-04-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_computer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Computer',
        ),
    ]
